spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:neighborhelp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: ${MAILPIT_SMTP_HOST:localhost}
    port: ${MAILPIT_SMTP_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    root: INFO
    org.springframework.security: INFO
